package:
  name: conda-data 
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  # use local path
  #git_url: https://github.com/srossross/conda-data
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  script: python setup.py install

requirements:
  build:
    - python
    - anaconda-client
    - odo

  run:
    - python
    - anaconda-client
    - odo
    - semantic_version

test:
  imports:
    - conda_data
   
about:
  home: https://github.com/srossross/conda-data
  license: BSD
  summary: "data-client for anaconda server"
